### ISSUE TITLE
Add Binary search in Java

### ISSUE THREAD

**Issue by Baba-Yaga-1** [adielliot37/dsa#19]

**Comment by nub-rin** [comment]
Is the algorithm for this done?

**Comment by adielliot37** [comment]
> Is the algorithm for this done?

I already assigned it to @Baba-Yaga-1 If he/she didnt respond I will assign it on FCFS
Thank You

**Comment by Baba-Yaga-1** [comment]
> > Is the algorithm for this done?
> 
> I already assigned it to @Baba-Yaga-1 If he/she didnt respond I will assign it on FCFS Thank You

Do I need to add notes as well with the code ?

**Comment by aniket2003** [comment]
Can you please assign me this . I have a good knowledge of Binary Search and Java.

**Comment by adielliot37** [comment]
> > > Is the algorithm for this done?
> > 
> > 
> > I already assigned it to @Baba-Yaga-1 If he/she didnt respond I will assign it on FCFS Thank You
> 
> Do I need to add notes as well with the code ?

just add comments where it is recquired

**Comment by adielliot37** [comment]
> Can you please assign me this . I have a good knowledge of Binary Search and Java.

you can apply for new issue for some different algo but make sure to you different languages like sol,python dont use c cpp java

**Comment by adielliot37** [comment]
@Baba-Yaga-1 has successfully submitted this issue
