### ISSUE TITLE
Adding Dynamic Programming and Backtracking algorithms CPP

### ISSUE THREAD

**Issue by suryaansh2002** [adielliot37/dsa#22]
I want to add Graph DP and Backtracking for CPP For hacktoberfest 2022. Please assign. Thanks

**Comment by adielliot37** [comment]
okay great go on please upload your own code Dont just copy paste 
and dont forget to star and fork the repo and follow me

**Comment by suryaansh2002** [comment]
Have created a PR

**Comment by adielliot37** [comment]
> Have created a PR

ok i will check and approve

**Comment by adielliot37** [comment]
@suryaansh2002 has successfully submitted code for this issue

**Comment by Faizan96322** [comment]
Hey, can I add knapsack problem in python for hacktoberfest 2022, pls assign this to me!

**Comment by adielliot37** [comment]
I have created a issue
https://github.com/adielliot37/dsa/issues/31#issue-1393798191
