### ISSUE TITLE
Basic Scheduling Algorithm

### ISSUE THREAD

**Issue by nub-rin** [adielliot37/dsa#35]
I can work on non-preemptive scheduling algorithm (for now, preemptive will we done later) in python. Kindly assign me this.
 - FCFS
 - SJF
 - Priority (non-preemptive)

**Comment by adielliot37** [comment]
Hey I can assign you but i will not add an label of hacktoberfest because I already merged your one pr with hacktober label 
else my account will be flagged
Thanks

**Comment by nub-rin** [comment]
Yes sure, no problem with me!!

**Comment by adielliot37** [comment]
ok then im closing this issue good luck
